stages:
  data_ingestion:
    cmd: python J:/Sentiment-Analysis/sentiment_analysis/components/data_ingestion.py
    deps:
    - J:/Sentiment-Analysis/sentiment_analysis/components/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python J:/Sentiment-Analysis/sentiment_analysis/components/data_transformation.py
    deps:
    - data/raw/train.csv
    - data/raw/test.csv
    - J:/Sentiment-Analysis/sentiment_analysis/components/data_transformation.py
    outs:
    - data/interim

  model_trainer:
    cmd: python J:/Sentiment-Analysis/sentiment_analysis/components/model_trainer.py
    deps:
    - data/interim/train_processed.csv
    - J:/Sentiment-Analysis/sentiment_analysis/components/model_trainer.py
    params:
    - model_building.max_features
    - model_building.ngram_range
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    outs:
    - lgbm_model.pkl
    - tfidf_vectorizer.pkl